apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispdfgen
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 2000Mi
    requests:
      cpu: 50m
      memory: 100Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    inbound:
      rules:
        - application: isaktivitetskrav
        - application: isfrisktilarbeid
        - application: isarbeidsuforhet
        - application: isdialogmote
        - application: isbehandlerdialog
        - application: ismanglendemedvirkning
        - application: isoppfolgingsplan
        - application: padm2
